start.sh :-

#/bin/sh
export ECS_INSTANCE_IP_ADDRES=S`curl -s 169.254.169.254/latest/meta-data/local-ipv4`
exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar
~


env.sh :-

#/bin/sh
ECS_INSTANCE_IP_ADDRESS=`curl -s 169.254.169.254/latest/meta-data/local-ipv4`







Dockerfile :-

FROM openjdk:8-jdk-alpine
VOLUME /tmp
VOLUME /logs
RUN apk upgrade
RUN apk --no-cache add curl
ADD Config-server-0.0.1-SNAPSHOT.jar app.jar
ADD start.sh start.sh
ENV JAVA_OPTS=""
EXPOSE 8888
ENTRYPOINT ["sh", "-c","/start.sh" ]

https://medium.com/flawless-app-stories/useful-git-commands-for-everyday-use-e1a4de64037d